// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dyoiffkhkxavuehffpws.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR5b2lmZmtoa3hhdnVlaGZmcHdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU5MTE2ODcsImV4cCI6MjA1MTQ4NzY4N30.l4WgMZVKO9wr5kwF292YIFluPgOkxsTUhzhSEGr1VXo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);